### PR TITLE
Create coord_app.md

### PR DESCRIPTION
**Pull request by LOZORD**
Still a work-in-progress. Thought people might want to see if before merging. :surfer:

### CODE REVIEW

**Comment by katamaritaco** [comment]
Can you add a link to the coord responsibilities doc within here?

**Comment by LOZORD** [comment]
@katamaritaco ready to merge?

**Comment by katamaritaco** [comment]
you can actually just leave out the path and put the filename since it is in same directory, but all good. Feel free to M E R G E :sweat_drops:

**Comment by LOZORD** [comment]
I'll merge, then update it :100:

**Comment by LOZORD** [comment]
@katamaritaco Actually, screw it, relative links are :ghost: . I keep on getting 404s. Feel free to change it yourself if you want.

**Pull request merged**
